name: doctor_perro_helper
description: "A Helper for Dr.Perro Food"
publish_to: "none"
version: 0.4.2

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_layout_grid: ^2.0.7
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.2
  haptic_feedback: ^0.5.1+1
  intl: ^0.20.1
  math_expressions: ^2.6.0
  native_toast: ^0.0.2
  provider: ^6.1.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.4.0
  swipeable_tile: ^2.0.1
  toastification: ^2.3.0
  flutter_native_splash: ^2.4.4
  easy_stepper: ^0.8.5+1
  data_table_2: ^2.5.18
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_background.jpg
    - assets/logos/doctor_perro_icon.png
    - assets/logos/logo_border_transparent.png
    - assets/logos/logo_transparent.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo_background.png"
  adaptive_icon_foreground: "assets/logos/logo_background.png"
  adaptive_icon_background: "#FD9D43"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FD9D43"
  image: "assets/logos/logo_border_transparent.png"
