name: doctor_perro_helper
description: "A Helper for Dr.Perro Food"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logos/logo_background.jpg
    - lib/assets/logos/logo_border_transparent.png
    - lib/assets/logos/logo_transparent.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logos/app_icon.png"
