name: doctor_perro_helper
description: "A Helper for Dr.Perro Food"
publish_to: "none"
version: 0.3.2

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_layout_grid: ^2.0.7
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.2
  haptic_feedback: ^0.5.1+1
  intl: ^0.20.1
  math_expressions: ^2.6.0
  native_toast: ^0.0.2
  provider: ^6.1.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.4.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logos/logo_background.jpg
    - lib/assets/logos/doctor_perro_icon.png
    - lib/assets/logos/logo_border_transparent.png
    - lib/assets/logos/logo_transparent.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logos/logo_background.png"
  adaptive_icon_foreground: "lib/assets/logos/logo_background.png"
  adaptive_icon_background: "#FFCC5EFF"
